### ISSUE TITLE
"Pick second hypothesis file" button can disappear

### ISSUE THREAD

**Issue by garfieldnate** [desilinguist/ibleu#5]
To reproduce:
1. Select hypothesis file.
2. Click "Compare to another system?"
3. Choose a different 1st hypothesis file
4. Click "Compare to another system?" again

Now the option for selecting a second hypothesis file will disappear, and you will have to reload the page in order to load all files.

**Comment by desilinguist** [comment]
I can't replicate this so I am closing it for now.
