### ISSUE TITLE
Chinese & Japanese Characters Issue

### ISSUE THREAD

**Issue by Debugger28** [desilinguist/ibleu#8]
I was trying to calculate BLEU score for the Chinese text. I am using a plain text file for the input. I am getting same BLEU score of 84.07 for every lines and the cumulative bleu score of 5.20 or something. 

All I want to say is that, it is showing wrong for every text, even if it is right. 

I am attaching both the reference & hypothesis files.
[GoogleEN-CN.txt](https://github.com/desilinguist/ibleu/files/1140344/GoogleEN-CN.txt)
[RefEN-CN.txt](https://github.com/desilinguist/ibleu/files/1140346/RefEN-CN.txt)

**Comment by desilinguist** [comment]
Interesting. I never really tested iBleu with Chinese translations. I'll
take a look soon.

**Comment by Debugger28** [comment]
Hello,

Did you got time to check out this issue? 

Thank you for your time.

**Comment by desilinguist** [comment]
Sorry, I've been swamped this week with some other things at work. I'll try
and take a look soon.

**Comment by desilinguist** [comment]
I looked at at this issue but the files you have attached seem to have a different number of lines. There should be a one-to-one correspondence between the number of lines in the hypothesis file and the number of lines in the reference file. Can you provide the appropriate files so I can test?

**Comment by Debugger28** [comment]
I am sorry about the wrong files. Here I have attached the new files.
[refEN-CNdemo.txt](https://github.com/desilinguist/ibleu/files/1183295/refEN-CNdemo.txt)
[canEN-CNdemo.txt](https://github.com/desilinguist/ibleu/files/1183296/canEN-CNdemo.txt)

Thank you for your time.

**Comment by desilinguist** [comment]
Yes, I see the problem now. I think the main issue is that my research on MT back in the day was always based on English as the target language and so iBLEU is not as well-tested on non-English target languages as it should be. I can try and fix this but it will probably require non-trivial modifications to the code and might take a few weeks. Unless some kind soul submits a PR first! :)

**Comment by Debugger28** [comment]
Thanks for the time. Yeah, I want to test for Chinese and Japanese languages. I'll be waiting for the modification. Exact similar error occurs with TILDE Bleu calculator https://www.letsmt.eu/Bleu.aspx. I cannot understand why there is an exact same error in both of them. 

Thanks again for your time.

**Comment by desilinguist** [comment]
Interesting. I didn't know about this tool. Looks pretty similar to iBLEU but it's not free.

**Comment by Debugger28** [comment]
I have been using this tool along with iBLEU. It never asked me for payment.

**Comment by desilinguist** [comment]
Is there a reason why you use both? They seem pretty similar to me.

**Comment by Debugger28** [comment]
Just to cross verify and I like some features in either of them.

**Comment by desilinguist** [comment]
I think the main problem is that the tokenization I have implemented (which I ported from the official BLEU script) only works for English. Do you have access to a Chinese segmenter? What happens if you run a segmenter on the hypothesis and reference sentences first and then given the segmented sentences to iBLEU as input?

**Comment by Debugger28** [comment]
Yes, this makes sense. I will try this out.

**Comment by desilinguist** [comment]
Any updates on this?

**Comment by Debugger28** [comment]
I was caught up last week. Will try to do it this week.

**Comment by desilinguist** [comment]
@Debugger28 please confirm if an external segmenter fixes the problem. I'd like to close this issue.

**Comment by Debugger28** [comment]
I did not get the time to test it. You can close the issue. I will try to test it next month, if the problem persists I will reach out to you.
